### ISSUE TITLE
Typing errors when starting/building create-hex-engine-game project

### ISSUE THREAD

**Issue by eramdam** [suchipi/hex-engine#47] opened 2020-05-17 04:21 UTC
Reproduction steps:

- `npx create-hex-engine-game@latest my-game`
- `cd my-game`
- `npm start`

Errors:

```
TypeScript error in /Users/damien/Desktop/my-game/node_modules/@hex-engine/2d/src/Canvas/index.ts(39,20):
Property 'msUserSelect' does not exist on type 'CSSStyleDeclaration'. Did you mean 'userSelect'?  TS2551

    37 |       document.body.appendChild(canvas);
    38 |       canvas.style.userSelect = "none";
  > 39 |       canvas.style.msUserSelect = "none";
       |                    ^
    40 |       canvas.style.webkitUserSelect = "none";
    41 |     }
    42 |     canvas.className = canvas.className + " " + "hex-engine";

TypeScript error in /Users/damien/Desktop/my-game/node_modules/@hex-engine/2d/src/Canvas/polyfillContext.ts(115,11):
This condition will always return true since the function is always defined. Did you mean to call it instead?  TS2774

    113 |     resetTransform() {
    114 |       matrix = createSVGMatrix();
  > 115 |       if (super.resetTransform) {
        |           ^
    116 |         super.resetTransform();
    117 |       } else {
```

I worked around those by adding `// @ts-ignore` in both cases but there's probably a proper way to fix those 🙈

**Comment by griimick** [comment] 2020-05-17 15:15
Properties of `CSSStyleDeclaration` such as `ms*`, etc have been removed from TypeScript 3.9 Beta and onwards. Also, `webkit*` properties have also been marked as deprecated. I am not aware of the reason at this moment and also could not find the exact discussion thread regarding this change.

**Comment by eramdam** [comment] 2020-05-17 16:38
> Properties of `CSSStyleDeclaration` such as `ms*`, etc have been removed from TypeScript 3.9 Beta and onwards. Also, `webkit*` properties have also been marked as deprecated. I am not aware of the reason at this moment and also could not find the exact discussion thread regarding this change.

That was my suspicion too but when I modified the project's package.json to use TypeScript 3.7.x instead of 3.9.x, the errors were still happening 🤷  But granted I didn't dig further and maybe `hex-engine-scripts` uses its own version of TS for the compilation instead of the one in the project 😅

**Comment by griimick** [comment] 2020-05-17 16:47
I am also surprised to see that they did not mention this in their [Breaking Changes Wiki](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#typescript-39). I looked into this a little bit more and found out that it has happened before also. There are some recommendations that they have mentioned in their wiki like the following,

- [https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#recommendations](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#recommendations)

**Comment by suchipi** [comment] 2020-05-19 22:52
Thanks for reporting this @eramdam, and thanks for digging into this, @griimick. I'll put `// @ts-ignore` on those in the repo's code, since hex engine can be used with multiple different typescript versions (but installs the latest by default).

**Closed** 2020-05-19 23:10 UTC
Labels: 2d, bug, create

**Comment by suchipi** [comment] 2020-05-19 23:15
Just confirmed this is now fixed; to fix it in your existing repo, bump `@hex-engine/2d` to `0.4.2` or higher.
