### ISSUE TITLE
Build failing on Win10 due to 'env'

### ISSUE THREAD

**Issue by arya-s** [suchipi/hex-engine#22] opened 2020-02-02 06:33 UTC
All engine packages fail with the following message on Win10 (non-WSL)
```
Building packages/core
packages/core: @workspace-builder/babel
'env' is not recognized as an internal or external command,operable program or batch file.
```

Works in WSL.

**Comment by suchipi** [comment] 2020-02-02 06:52
Thanks; looks like the cause is in [@workspace-builder/babel](https://github.com/suchipi/workspace-builder/blob/master/packages/babel/index.js#L27). I'll swap that out for cross-env.

**Comment by arya-s** [comment] 2020-02-02 07:03
Should I file it over there?

**Comment by suchipi** [comment] 2020-02-02 07:08
Nah, that's alright, I already fixed it (that other repo is mine, too)

**Comment by suchipi** [comment] 2020-02-02 07:09
Testing that it fixed the win10 build in hex-engine and then I'll close this

**Comment by suchipi** [comment] 2020-02-02 07:17
Alright, with 7f32a5eba67a746246576bc53baf9fe867be6ac3 and 5154f10e0025f326b5a837b915b4fb80d1efef85, the build and dev scripts work on windows now :D

**Closed by suchipi** 2020-02-02 07:17 UTC

**Comment by arya-s** [comment] 2020-02-02 07:22
Can confirm, works!
